import { ProduceItem } from '@/types';

export const PRODUCE_CATALOG: ProduceItem[] = [
  {
    id: 'prod_1',
    key: 'veg_tomato',
    imageUrl: 'https://images.pexels.com/photos/33499935/pexels-photo-33499935.jpeg',
    category: 'daily',
    name: {
      en: 'Country Tomato (Naatu Thakkali)',
      ta: 'நாட்டு தக்காளி',
      te: 'నాటు టమోటా',
      ml: 'നാടൻ തക്കാളി',
      hi: 'देसी टमाटर',
    },
    subtitle: {
      en: 'Fresh Red Harvest',
      ta: 'பழம்',
      te: 'పండు',
      ml: 'പഴം',
      hi: 'पका हुआ',
    },
    baseBenchmarkPrice: 32,
    unit: 'kg',
    shelfLifeDays: 5,
    perishabilityIndex: 'High',
    defaultGrade: 'Grade A',
  },
  {
    id: 'prod_2',
    key: 'veg_onion',
    imageUrl: 'https://images.pexels.com/photos/38088072/pexels-photo-38088072.jpeg',
    category: 'daily',
    name: {
      en: 'Farm Onion / Shallots (Vengayam)',
      ta: 'வெங்காயம்',
      te: 'ఉల్లిపాయలు',
      ml: 'ഉള്ളി',
      hi: 'प्याज',
    },
    subtitle: {
      en: 'Small Onion',
      ta: 'சின்ன வெங்காயம்',
      te: 'చిన్న ఉల్లిపాయ',
      ml: 'ചെറിയ ഉള്ളി',
      hi: 'छोटा प्याज',
    },
    baseBenchmarkPrice: 36,
    unit: 'kg',
    shelfLifeDays: 14,
    perishabilityIndex: 'Low',
    defaultGrade: 'Grade A',
  },
  {
    id: 'prod_3',
    key: 'veg_potato',
    imageUrl: 'https://images.pexels.com/photos/7774212/pexels-photo-7774212.jpeg',
    category: 'daily',
    name: {
      en: 'Hill Potato (Urulaikizhangu)',
      ta: 'உருளைக்கிழங்கு',
      te: 'బంగాళాదుంప',
      ml: 'ഉരുളക്കിഴങ്ങ്',
      hi: 'आलू',
    },
    subtitle: {
      en: 'Clean Harvest',
      ta: 'பெங்களூர்',
      te: 'బెంగళూరు',
      ml: 'ബാംഗ്ലൂർ',
      hi: 'पहाड़ी आलू',
    },
    baseBenchmarkPrice: 30,
    unit: 'kg',
    shelfLifeDays: 20,
    perishabilityIndex: 'Low',
    defaultGrade: 'Grade A',
  },
  {
    id: 'prod_4',
    key: 'veg_carrot',
    imageUrl: 'https://images.pexels.com/photos/1306559/pexels-photo-1306559.jpeg',
    category: 'daily',
    name: {
      en: 'Fresh Carrot (Carrot)',
      ta: 'கேரட்',
      te: 'క్యారెట్',
      ml: 'കാരറ്റ്',
      hi: 'गाजर',
    },
    subtitle: {
      en: 'Ooty Fresh',
      ta: 'ஊட்டி கேரட்',
      te: 'ఊటీ క్యారెట్',
      ml: 'ഊട്ടി കാരറ്റ്',
      hi: 'ताज़ा गाजर',
    },
    baseBenchmarkPrice: 45,
    unit: 'kg',
    shelfLifeDays: 8,
    perishabilityIndex: 'Medium',
    defaultGrade: 'Grade A',
  },
  {
    id: 'prod_5',
    key: 'veg_beans',
    imageUrl: 'https://images.pexels.com/photos/34387471/pexels-photo-34387471.jpeg',
    category: 'daily',
    name: {
      en: 'French Beans (Avarai / Beans)',
      ta: 'பீன்ஸ் / அவரை',
      te: 'చిక్కుడు / బీన్స్',
      ml: 'ബീൻസ്',
      hi: 'हरी बीन्स',
    },
    subtitle: {
      en: 'Tender Pods',
      ta: 'கொத்தவரை',
      te: 'గోర చిక్కుడు',
      ml: 'കൊത്തമര',
      hi: 'ताज़ा फली',
    },
    baseBenchmarkPrice: 55,
    unit: 'kg',
    shelfLifeDays: 4,
    perishabilityIndex: 'High',
    defaultGrade: 'Grade A',
  },
  {
    id: 'prod_6',
    key: 'fruit_mango',
    imageUrl: 'https://images.pexels.com/photos/37816783/pexels-photo-37816783.jpeg',
    category: 'fruits',
    name: {
      en: 'Sweet Mango (Banganapalli / Mambazham)',
      ta: 'மாம்பழம்',
      te: 'మామిడి పండు',
      ml: 'മാമ്പഴം',
      hi: 'आम',
    },
    subtitle: {
      en: 'Farm Ripe',
      ta: 'பங்கனபள்ளி',
      te: 'బంగినపల్లి',
      ml: 'ബംഗനപ്പള്ളി',
      hi: 'मीठा आम',
    },
    baseBenchmarkPrice: 65,
    unit: 'kg',
    shelfLifeDays: 6,
    perishabilityIndex: 'High',
    defaultGrade: 'Grade A',
  },
  {
    id: 'prod_7',
    key: 'fruit_banana',
    imageUrl: 'https://images.pexels.com/photos/10112720/pexels-photo-10112720.jpeg',
    category: 'fruits',
    name: {
      en: 'Native Banana (Poovan / Vazhaipazham)',
      ta: 'வாழைப்பழம்',
      te: 'అరటి పండు',
      ml: 'വാഴപ്പഴം',
      hi: 'केला',
    },
    subtitle: {
      en: 'Golden Bunch',
      ta: 'பூவன்',
      te: 'పూవన్',
      ml: 'പൂവൻ',
      hi: 'देशी केला',
    },
    baseBenchmarkPrice: 38,
    unit: 'kg',
    shelfLifeDays: 5,
    perishabilityIndex: 'High',
    defaultGrade: 'Grade A',
  },
  {
    id: 'prod_8',
    key: 'fruit_guava',
    imageUrl: 'https://images.pexels.com/photos/8668726/pexels-photo-8668726.jpeg',
    category: 'fruits',
    name: {
      en: 'Country Guava (Koyyapazham)',
      ta: 'கொய்யாப்பழம்',
      te: 'జామ పండు',
      ml: 'പേരയ്ക്ക',
      hi: 'अमरूद',
    },
    subtitle: {
      en: 'Farm Crisp',
      ta: 'நாட்டு கொய்யா',
      te: 'నాటు జామ',
      ml: 'നാടൻ പേരയ്ക്ക',
      hi: 'ताज़ा अमरूद',
    },
    baseBenchmarkPrice: 42,
    unit: 'kg',
    shelfLifeDays: 6,
    perishabilityIndex: 'Medium',
    defaultGrade: 'Grade A',
  },
];

export function getProduceByKey(key: string): ProduceItem | undefined {
  return PRODUCE_CATALOG.find((item) => item.key === key);
}

export function getProduceById(id: string): ProduceItem | undefined {
  return PRODUCE_CATALOG.find((item) => item.id === id);
}
