import {
  UserProfile,
  FarmerLot,
  AggregatedBatch,
  BuyerDemand,
  TransitMission,
  SettlementRecord,
  CommunityCluster,
  SubscriptionBasket,
} from '@/types';

export const DEMO_USERS: Record<string, UserProfile> = {
  farmer: {
    id: 'usr_farmer_01',
    role: 'farmer',
    identifier: 'TN-SLM-FARM-4821',
    name: 'Balamurugan',
    location: 'Dindigul / Salem Rural Cluster, Tamil Nadu',
    accountNumber: '••••••••4821',
    ifscCode: 'SBI0001245',
    avatarSeed: 'balamurugan',
  },
  fpo: {
    id: 'usr_fpo_01',
    role: 'fpo',
    identifier: 'FPO-TN-ERD-1092',
    name: 'Salem-Erode Farmers Producer Co.',
    location: 'Perundurai Agri Hub, Salem-Erode Hwy',
    avatarSeed: 'fpo_manager',
  },
  buyer: {
    id: 'usr_buyer_01',
    role: 'buyer',
    identifier: '33AABCT9981Q1Z5',
    name: 'Koyambedu Wholesale Agro Direct',
    location: 'Koyambedu Wholesale Complex, Chennai',
    avatarSeed: 'buyer_chennai',
  },
  consumer: {
    id: 'usr_consumer_01',
    role: 'consumer',
    identifier: 'CONSUMER-FRESH-01',
    name: 'Ananya Sharma',
    location: 'Green Valley Apartments, Salem',
    clusterId: 'cluster_salem_01',
    avatarSeed: 'ananya_consumer',
  },
  logistics: {
    id: 'usr_logistics_01',
    role: 'logistics',
    identifier: 'TN-LOG-TRUCK-88',
    name: 'Selvam Reefer Express Fleet',
    location: 'Salem - Dharmapuri - Chennai Corridor',
    avatarSeed: 'driver_selvam',
  },
  admin: {
    id: 'usr_admin_01',
    role: 'admin',
    identifier: 'ADMIN-AGRICONNECT-01',
    name: 'AgriConnect Governance & Escrow Desk',
    location: 'Chennai Central State Hub',
    avatarSeed: 'admin_root',
  },
};

export const COMMUNITY_CLUSTERS: CommunityCluster[] = [
  {
    id: 'cluster_salem_01',
    name: 'Green Valley Apartments, Salem',
    location: 'Fairlands, Salem',
    activeHouseholds: 42,
    currentPooledKg: 340,
    targetThresholdKg: 500,
    discountPercentage: 20,
    hubOrigin: 'Salem FPO Aggregation Hub (6 km away)',
  },
  {
    id: 'cluster_erode_02',
    name: 'Mayflower Heights Society, Erode',
    location: 'Perundurai Road, Erode',
    activeHouseholds: 56,
    currentPooledKg: 460,
    targetThresholdKg: 500,
    discountPercentage: 20,
    hubOrigin: 'Perundurai Consolidation Depot',
  },
];

export const INITIAL_FARMER_LOTS: FarmerLot[] = [
  {
    id: 'lot_slm_101',
    farmerId: 'usr_farmer_01',
    farmerName: 'Balamurugan',
    farmerPhone: '+91 98421 76540',
    farmerLocation: 'Dindigul / Salem Rural Cluster, Tamil Nadu',
    produceId: 'prod_1',
    produceKey: 'veg_tomato',
    quantityKg: 500,
    grade: 'Grade A',
    expectedPricePerKg: 32,
    grossEstimatedValue: 16000,
    sharedLogisticsCost: 900,
    fpoHandlingCost: 200,
    platformCoordinationFee: 240,
    netEstimatedCashInHand: 14660,
    status: 'Settled',
    createdAt: '2026-09-28T07:30:00Z',
    voiceRecorded: true,
  },
  {
    id: 'lot_slm_102',
    farmerId: 'usr_farmer_01',
    farmerName: 'Balamurugan',
    farmerPhone: '+91 98421 76540',
    farmerLocation: 'Dindigul / Salem Rural Cluster, Tamil Nadu',
    produceId: 'prod_2',
    produceKey: 'veg_onion',
    quantityKg: 850,
    grade: 'Grade A',
    expectedPricePerKg: 36,
    grossEstimatedValue: 30600,
    sharedLogisticsCost: 1530,
    fpoHandlingCost: 340,
    platformCoordinationFee: 459,
    netEstimatedCashInHand: 28271,
    status: 'InTransit',
    createdAt: '2026-09-29T06:15:00Z',
    voiceRecorded: true,
    assignedBatchId: 'batch_erd_501',
  },
  {
    id: 'lot_slm_103',
    farmerId: 'usr_farmer_02',
    farmerName: 'Muthuvel Karuppan',
    farmerPhone: '+91 98431 10928',
    farmerLocation: 'Pennagaram, Dharmapuri',
    produceId: 'prod_4',
    produceKey: 'veg_carrot',
    quantityKg: 400,
    grade: 'Grade A',
    expectedPricePerKg: 45,
    grossEstimatedValue: 18000,
    sharedLogisticsCost: 720,
    fpoHandlingCost: 160,
    platformCoordinationFee: 270,
    netEstimatedCashInHand: 16850,
    status: 'Batched',
    createdAt: '2026-09-30T05:45:00Z',
  },
  {
    id: 'lot_slm_104',
    farmerId: 'usr_farmer_03',
    farmerName: 'Kandasamy Thevar',
    farmerPhone: '+91 97890 33412',
    farmerLocation: 'Kaveripattinam, Krishnagiri',
    produceId: 'prod_6',
    produceKey: 'fruit_mango',
    quantityKg: 1200,
    grade: 'Grade A',
    expectedPricePerKg: 65,
    grossEstimatedValue: 78000,
    sharedLogisticsCost: 2160,
    fpoHandlingCost: 480,
    platformCoordinationFee: 1170,
    netEstimatedCashInHand: 74190,
    status: 'Verified',
    createdAt: '2026-09-30T06:30:00Z',
  },
];

export const INITIAL_AGGREGATED_BATCHES: AggregatedBatch[] = [
  {
    id: 'batch_erd_501',
    fpoId: 'usr_fpo_01',
    fpoName: 'Salem-Erode Farmers Producer Co.',
    hubLocation: 'Salem FPO Consolidation Hub',
    produceId: 'prod_1',
    produceKey: 'veg_tomato',
    totalWeightKg: 5000,
    lotIds: ['lot_slm_101', 'lot_slm_105', 'lot_slm_106'],
    grade: 'Grade A',
    fpoBasePricePerKg: 32,
    targetBuyerSegment: 'Direct Wholesale Hubs (Chennai Koyambedu)',
    status: 'ReadyForBuyer',
    clusteringCompatibilityScore: 98,
    createdAt: '2026-09-29T10:00:00Z',
    transshipmentHops: 0,
  },
  {
    id: 'batch_erd_502',
    fpoId: 'usr_fpo_01',
    fpoName: 'Salem-Erode Farmers Producer Co.',
    hubLocation: 'Dharmapuri Aggregation Depot',
    produceId: 'prod_2',
    produceKey: 'veg_onion',
    totalWeightKg: 4500,
    lotIds: ['lot_slm_102'],
    grade: 'Grade A',
    fpoBasePricePerKg: 36,
    targetBuyerSegment: 'Tier-1 B2B Retail & Institutional Buyers',
    status: 'Matched',
    clusteringCompatibilityScore: 95,
    createdAt: '2026-09-29T14:30:00Z',
    transshipmentHops: 0,
  },
  {
    id: 'batch_erd_503',
    fpoId: 'usr_fpo_01',
    fpoName: 'Salem-Erode Farmers Producer Co.',
    hubLocation: 'Krishnagiri Mango & Fruit Cluster',
    produceId: 'prod_6',
    produceKey: 'fruit_mango',
    totalWeightKg: 6000,
    lotIds: ['lot_slm_104'],
    grade: 'Grade A',
    fpoBasePricePerKg: 65,
    targetBuyerSegment: 'Metro Fruit Mandi & Export Packhouses',
    status: 'Aggregating',
    clusteringCompatibilityScore: 92,
    createdAt: '2026-09-30T08:00:00Z',
    transshipmentHops: 0,
  },
];

export const INITIAL_BUYER_DEMANDS: BuyerDemand[] = [
  {
    id: 'demand_chn_901',
    buyerId: 'usr_buyer_01',
    buyerName: 'Koyambedu Wholesale Agro Direct',
    destinationHub: 'Koyambedu Wholesale Complex, Chennai',
    produceId: 'prod_1',
    produceKey: 'veg_tomato',
    requiredWeightKg: 5000,
    acceptableGrade: 'Grade A',
    targetMaxPricePerKg: 33.5,
    deliveryWindowHours: 12,
    deliveryDate: '2026-10-01',
    specialInstructions: 'Cold-chain reefer mandatory. Palletized delivery in 20kg returnable plastic crates.',
    status: 'Open',
    createdAt: '2026-09-30T04:00:00Z',
    matchedBatchId: 'batch_erd_501',
    compatibilityScore: 96,
  },
  {
    id: 'demand_chn_902',
    buyerId: 'usr_buyer_01',
    buyerName: 'Koyambedu Wholesale Agro Direct',
    destinationHub: 'Koyambedu Wholesale Complex, Chennai',
    produceId: 'prod_2',
    produceKey: 'veg_onion',
    requiredWeightKg: 4500,
    acceptableGrade: 'Grade A',
    targetMaxPricePerKg: 38,
    deliveryWindowHours: 18,
    deliveryDate: '2026-10-02',
    specialInstructions: 'Direct dock delivery at Koyambedu Bay 4.',
    status: 'ContractSigned',
    createdAt: '2026-09-29T12:00:00Z',
    matchedBatchId: 'batch_erd_502',
    compatibilityScore: 94,
  },
];

export const INITIAL_SUBSCRIPTION_BASKET: SubscriptionBasket = {
  id: 'sub_basket_01',
  name: "Farmer's Daily Essentials Fresh Basket",
  frequency: 'daily',
  timeSlot: '6:00 AM - 7:30 AM',
  startDate: 'Tomorrow Morning',
  items: [
    { produceKey: 'veg_tomato', quantityKg: 1.0 },
    { produceKey: 'veg_onion', quantityKg: 1.0 },
    { produceKey: 'veg_potato', quantityKg: 1.0 },
    { produceKey: 'veg_carrot', quantityKg: 0.5 },
  ],
  monthlyEstimateRupees: 2840,
  monthlySupermarketSavings: 1120,
  isActive: true,
};

export const INITIAL_TRANSIT_MISSION: TransitMission = {
  id: 'msn_corridor_8812',
  batchId: 'batch_erd_502',
  buyerDemandId: 'demand_chn_902',
  truckNumber: 'TN-30-AZ-8812',
  driverName: 'M. Murugesan (+91 98421 77210)',
  originHub: 'Salem FPO Consolidation Hub',
  destinationHub: 'Koyambedu Wholesale Market, Chennai',
  produceKey: 'veg_onion',
  totalWeightKg: 4500,
  telemetry: {
    truckNumber: 'TN-30-AZ-8812',
    driverName: 'M. Murugesan',
    driverPhone: '+91 98421 77210',
    reeferTemperature: 12.4,
    targetTempMin: 8.0,
    targetTempMax: 14.0,
    relativeHumidity: 88,
    vehicleSpeedKmH: 54,
    currentCoordinates: [12.5255, 78.2144],
    remainingDistanceKm: 238,
    etaHours: 4.5,
    originHub: 'Salem FPO Hub',
    destinationHub: 'Chennai Koyambedu',
    currentMilestone: 'InTransit',
    updatedAt: new Date().toISOString(),
  },
  milestonesHistory: [
    {
      milestone: 'Scheduled',
      timestamp: '2026-09-30T04:30:00Z',
      completed: true,
      locationNote: 'Salem Consolidation Yard (Vehicle Dispatched)',
    },
    {
      milestone: 'PickedUp',
      timestamp: '2026-09-30T06:00:00Z',
      completed: true,
      locationNote: 'Loaded 4,500 kg Shallots & Temperature Pre-Cooled to 12°C',
    },
    {
      milestone: 'InTransit',
      timestamp: '2026-09-30T08:15:00Z',
      completed: true,
      locationNote: 'Crossing Krishnagiri Highway Corridor at 54 km/h',
    },
    {
      milestone: 'Delivered',
      timestamp: 'Pending',
      completed: false,
      locationNote: 'Chennai Koyambedu Receiving Bay 4',
    },
    {
      milestone: 'Settled',
      timestamp: 'Pending',
      completed: false,
      locationNote: 'Automatic Escrow Release to Smallholder Bank Accounts',
    },
  ],
  status: 'Active',
};

export const INITIAL_SETTLEMENT_RECORD: SettlementRecord = {
  id: 'stl_tx_998124',
  lotId: 'lot_slm_101',
  farmerId: 'usr_farmer_01',
  farmerName: 'Balamurugan',
  produceKey: 'veg_tomato',
  quantityKg: 500,
  clearedRatePerKg: 32.0,
  grossClearedValue: 16000.0,
  sharedRouteFreight: 900.0,
  fpoWeighmentStorage: 200.0,
  platformFee: 240.0,
  farmerNetCashInHand: 14660.0,
  effectiveRatePerKg: 29.32,
  villageBrokerBaselineRate: 19.2,
  villageBrokerGross: 9600.0,
  farmerSurplusGainRupees: 5060.0,
  farmerSurplusGainPercentage: 52.7,
  payoutStatus: 'Transferred to Bank Account (T+24h)',
  bankReferenceNumber: 'UTR-AGRI-20260930-SBI-883921',
  settledAt: '2026-09-29T18:30:00Z',
};
